modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/simply-kel/ruthenium/issues"
license="MIT"

[[mods]]
displayTest = "IGNORE_ALL_VERSION"
modId = "example"
version = "${project.version}"
displayURL = "https://modrinth.com/mod/example"
displayName = "Example"
updateJSONURL = "https://api.modrinth.com/updates/example/forge_updates.json"
authors = "Im_Kel"
description = "Example desciption"
logoFile = "assets/example/logo.png"

[[dependencies.example]]
modId = "forge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "alinlib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.example]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"